[env]
TERM = "xterm-256color"

[window]
padding.x = 20
padding.y = 20
decorations = "None" 

opacity = 0.8
blur = false

[font]
normal.family = "Fira Code"
size = 10.0
#bold = true
#italic = true
#offset_x = 0.0 
#offset_y = 0.0 

#[cursor]
#style = "Beam"
#blink = true  

#[[key_bindings]]
#key = "Equals"
#mods = "Control"
#action = "IncreaseFontSize"

#[[key_bindings]]
#key = "Minus"
#mods = "Control"
#action = "DecreaseFontSize"
